# Generated by Django 3.2.4 on 2021-06-19 14:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orphanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('UserName', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('UserBirthday', models.DateField(default=datetime.date.today)),
                ('UserNationalID', models.CharField(max_length=200)),
                ('UserArea', models.CharField(max_length=200)),
                ('UserStreet', models.CharField(max_length=200)),
                ('UserProfile', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('UserCityID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orphanage.citymodel')),
                ('UserCountryID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orphanage.countrymodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserStatusModel',
            fields=[
                ('UserStatusID', models.AutoField(primary_key=True, serialize=False)),
                ('UserStatusName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserTypeModel',
            fields=[
                ('UserTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('UserTypeName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoneModel',
            fields=[
                ('UserPhoneID', models.AutoField(primary_key=True, serialize=False)),
                ('UserPhone', models.CharField(max_length=30)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sponser.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='UserStatusID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sponser.userstatusmodel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='UserTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sponser.usertypemodel'),
        ),
    ]
