# Generated by Django 3.2.4 on 2021-06-19 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0002_initial'),
        ('sponser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='UserCityID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orphanage.citymodel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='UserCountryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orphanage.countrymodel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='UserStatusID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sponser.userstatusmodel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='UserTypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sponser.usertypemodel'),
        ),
    ]
