# Generated by Django 3.2.4 on 2021-06-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('PaymenID', models.AutoField(primary_key=True, serialize=False)),
                ('PayAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('PayDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('RequestID', models.AutoField(primary_key=True, serialize=False)),
                ('RequestTypeID', models.IntegerField()),
                ('FileUpload', models.CharField(blank=True, max_length=300)),
                ('Date', models.DateField(auto_now_add=True)),
                ('RootRequestID', models.IntegerField()),
                ('RequestStatusID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('RequestStatusID', models.AutoField(primary_key=True, serialize=False)),
                ('RequestStatusName', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('RequestTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('RequestTypeName', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
