# Generated by Django 3.2.4 on 2021-06-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponser', '0001_initial'),
        ('admin_kafala', '0001_initial'),
        ('orphanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='ChildID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='orphanage.childrensmodel'),
        ),
        migrations.AddField(
            model_name='requests',
            name='OrphanageID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='orphanage.orphanagemodel'),
        ),
        migrations.AddField(
            model_name='requests',
            name='UserID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='sponser.usermodel'),
        ),
        migrations.AddField(
            model_name='payments',
            name='RequestID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='admin_kafala.requests'),
        ),
        migrations.AddField(
            model_name='payments',
            name='UserID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='sponser.usermodel'),
        ),
    ]
