# Generated by Django 3.2.4 on 2021-07-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kafala', '0007_alter_requests_requestdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='RequestFileUpload',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
