# Generated by Django 3.2.4 on 2021-07-17 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kafala', '0008_alter_requests_requestfileupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='RootRequestID',
        ),
    ]
