# Generated by Django 3.2.4 on 2021-06-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionTypeModel',
            fields=[
                ('AdoptionTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('AdoptionTypeName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ChildImageModel',
            fields=[
                ('ChildImageID', models.AutoField(primary_key=True, serialize=False)),
                ('ChildImage', models.ImageField(blank=True, null=True, upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='ChildrensModel',
            fields=[
                ('ChildID', models.AutoField(primary_key=True, serialize=False)),
                ('RealName', models.CharField(blank=True, max_length=250)),
                ('NationalID', models.CharField(blank=True, max_length=12)),
                ('HisDream', models.CharField(blank=True, max_length=250)),
                ('BirthDate', models.DateField(null=True)),
                ('CostPrice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('CaseHistory', models.CharField(blank=True, max_length=500)),
                ('HealthStatus', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OrphanageModel',
            fields=[
                ('OrphanageID', models.AutoField(primary_key=True, serialize=False)),
                ('CEO', models.IntegerField(default=0)),
                ('Description', models.CharField(blank=True, max_length=1000)),
                ('PermissionNo', models.CharField(max_length=250)),
                ('CommercialNo', models.CharField(max_length=250)),
                ('StartDate', models.DateField()),
                ('Website', models.CharField(max_length=500)),
                ('Notes', models.CharField(max_length=500)),
                ('CityID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='orphanage.citymodel')),
            ],
        ),
    ]
