# Generated by Django 3.2.4 on 2021-06-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponser', '0001_initial'),
        ('orphanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanagemodel',
            name='UserID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='sponser.usermodel'),
        ),
        migrations.AddField(
            model_name='childrensmodel',
            name='AdoptionTypeID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='orphanage.adoptiontypemodel'),
        ),
        migrations.AddField(
            model_name='childrensmodel',
            name='OrphanageID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orphanage.orphanagemodel'),
        ),
        migrations.AddField(
            model_name='childimagemodel',
            name='ChildID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='child_id', to='orphanage.childrensmodel'),
        ),
    ]
