# Generated by Django 3.2.4 on 2021-07-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphanagemodel',
            name='CEO',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
