# Generated by Django 3.2.4 on 2021-07-16 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0004_alter_childrensmodel_orphanageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrensmodel',
            name='OrphanageID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orphanage.orphanagemodel'),
        ),
    ]
