# Generated by Django 3.2.4 on 2021-07-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0007_auto_20210716_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrensmodel',
            name='AdoptionTypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orphanage.adoptiontypemodel'),
        ),
    ]
